### ISSUE TITLE
modificar columnas pantalla de usuario

### ISSUE THREAD

**Issue by rvargassanhueza** [rvargassanhueza/front-admin-guiacomercial#2]
se debe quitar la columna id_usuario y agregar la columna tipo de usuario

**Comment by edvalenzuela** [comment]
solo estan los id (number) del tipo de usuario, no los nombres al consultar el get de usuarios @rvargassanhueza

**Comment by rvargassanhueza** [comment]
tienes razón, debo hacer un ajuste a la api

**Comment by rvargassanhueza** [comment]
está listo eduardo, ahora los datos que aparecen son: 
![image](https://user-images.githubusercontent.com/17125189/128569663-c1214758-ab17-466a-bf28-f1d54a8cb838.png)

**Comment by edvalenzuela** [comment]
#### Adjunto captura de los datos
![image](https://user-images.githubusercontent.com/39087254/128804470-780291a0-38b1-4152-8679-f11349f5a988.png)

**Funcionando**  los nuevos datos del back end con el nombre_tipo_usuario :v: @rvargassanhueza
