### ISSUE TITLE
agregar campo contraseña y confirmar contraseña en modal de insertar usuarios

### ISSUE THREAD

**Issue by rvargassanhueza** [rvargassanhueza/front-admin-guiacomercial#3]

**Comment by edvalenzuela** [comment]
Campo confirmar contraseña no esta en el get de usuarios @rvargassanhueza

**Comment by rvargassanhueza** [comment]
se trata de la comparación de ambos campos de texto para validar si la contraseña creada está correcta.

contraseña:
confirme contraseña:

esto es al momento de crear un usuario

se comparan ambos, si están iguales pasa la contraseña

**Comment by edvalenzuela** [comment]
## Funcionando en el último **commit 2089b4d** y quedando insertando nuevos usuarios @rvargassanhueza 
![image](https://user-images.githubusercontent.com/39087254/128822748-099b5a39-3f16-4b12-8658-b9f473377447.png)
