### ISSUE TITLE
editar en componente usuarios

### ISSUE THREAD

**Issue by rvargassanhueza** [rvargassanhueza/front-admin-guiacomercial#5]

**Comment by edvalenzuela** [comment]
Esta funcionando el método EditarUsuarios( ) solo falta capturar más datos necesarios para llenar todo el modal de editar

## Demo captura
![image](https://user-images.githubusercontent.com/39087254/129520861-11ba5b3f-bfd2-4ba2-9fdf-928fa1889e37.png)

**Comment by rvargassanhueza** [comment]
Debes hacer un llamado al end point pasando el id del usuario, ejemplo:

http://localhost:3002/v1/usuario/1995

![image](https://user-images.githubusercontent.com/17125189/129606571-2d4b5461-f5d5-4885-83e5-ad30bb5f2a0e.png)

**Comment by edvalenzuela** [comment]
Este issue, déjalo en modo **Pendiente** por el momento _**getEditarUsuarioByID**_ @rvargassanhueza

**Comment by edvalenzuela** [comment]
Solucionado este issue en el Commit 3467e37026f1b8c375523f1f2939f03f3d8f5471 @rvargassanhueza
